### ISSUE TITLE
allow toggling

### ISSUE THREAD

**Issue by FekketCantenel** [Poucous/smartReader#1]
Please add a way to easily enable/disable the addon by website, and a way to either bionify the text by default or only bionify it on toggle. I'm picturing how the Firefox addon Dark Mode by Bernard provides a handy toolbar toggle button.

**Comment by Poucous** [comment]
Hello, I'm working on the toolbar button and others little things to fix, we should be able to disable the extension by clicking on it very soon.
For enable or disable the addon by website, it's longer, and it will come if there are more users.

Thank you.

**Comment by Poucous** [comment]
Hi, 
I added the extension on the toolbar (I will try to improve it further), for adding a way to easily enable/disable the addon by website, I added it to the fresh created to-do list.

**Comment by Poucous** [comment]
Hi, 
I added the extension on the toolbar (I will try to improve it further), for adding a way to easily enable/disable the addon by website, I added it to the fresh created to-do list.
