### ISSUE TITLE
Why doesn't it work on Hacker News?

### ISSUE THREAD

**Issue by themightyoarfish** [Poucous/smartReader#12]
**Describe the bug**

Not sure if bug or feature request, but the app does not work on hacker news comment threads.

**To Reproduce**
1. https://news.ycombinator.com/item?id=35335240
2. Enable extension

**Expected behavior**
Bionic highlighting applied

**Desktop (please complete the following information):**
 - OS: macos 12.5.1
 - Browser Firefox 
 - Version 111.0.1

**Comment by Poucous** [comment]
Hello, I see that this site does not have the basic tag for a website: <!doctype html>
So the page is in a compatibility mode (quirks), this is probably the cause.
