### ISSUE TITLE
ignoring italicized text

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [Poucous/smartReader#6]
Here's an example page :
![image](https://user-images.githubusercontent.com/26625900/172120815-70acae32-764f-425e-a7b4-364d6f58e25e.png)
https://www.lemonde.fr/blog/realitesbiomedicales/2022/06/04/monkeypox-ce-quon-sait-des-premiers-cas-survenus-en-france-aux-etats-unis-au-royaume-uni-au-portugal-en-italie-et-en-australie/

**Comment by Poucous** [comment]
Hello, I added italic text, I will push an update soon.
